title: News from london
email: gramulos@gmail.com
description: A daily journal by Edwars Hyde
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: rdiscount
rdiscount:
  extensions: [smart]
premalink: /articles/:title
