title: News from london
email: gramulos@gmail.com
description: A daily journal by Edwars Hyde
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
premalink: /articles/:title
