title: News from london
email: gramulos@gmail.com
description: A daily journal by Edwars Hyde
baseurl: "/london-news"
url: "http://localhost:4000"

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
premalink: /articles/:title
paginate: 3
